# Generated by Django 5.2.8 on 2025-11-10 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flower',
            name='category',
        ),
        migrations.DeleteModel(
            name='FlowerCategory',
        ),
    ]
